version: '3'
services:
  api:
    build: .
    ports:
      - "3000:3000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    labels:
      - "monitoring.port=3000"  # Prometheus will scrape this port

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml  # Configuration file for Prometheus
    ports:
      - "9090:9090"  # Exposing Prometheus on port 9090
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"  # Specifying config file
