# .github/workflows/ci.yml

name: CI Pipeline for DevOps API

on:
  push:
    branches:
      - 'main'
    tags:
      - '*'

jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: pip install flake8

      - name: Run Linter
        run: flake8 .

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run Tests
        run: pytest

  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker Image with Latest Tag
        run: |
          TAG=$(git describe --tags --abbrev=0)
          docker build -t devops-api:${TAG} .
  
  helm-package:
    name: Package Helm Chart
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

      - name: Package Helm Chart
        run: |
          helm package ./helm/devops-api

      - name: Upload Helm Chart as Artifact
        uses: actions/upload-artifact@v2
        with:
          name: devops-api-helm-chart
          path: ./devops-api-0.1.0.tgz
